# Generated by Django 3.2.18 on 2023-03-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_auto_20230307_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='sub_type',
            field=models.CharField(choices=[('none', 'N/A'), ('procure', 'Procurement'), ('project', 'Project Manager'), ('assurance', 'Information Assure'), ('developer', 'Developer'), ('sustain', 'Sustainment'), ('operator', 'Operator'), ('lead', 'Lead')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='approver',
            name='type',
            field=models.CharField(choices=[('client', 'Client'), ('integrator', 'Systems Integrator'), ('authority', 'Authority'), ('vendor', 'Vendor')], max_length=20),
        ),
    ]
