# Generated by Django 3.2.18 on 2023-03-10 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0006_auto_20230308_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='users',
        ),
        migrations.AddField(
            model_name='program',
            name='members',
            field=models.ManyToManyField(related_name='programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='program',
            name='default_approvers',
            field=models.ManyToManyField(related_name='default_approvers', to=settings.AUTH_USER_MODEL),
        ),
    ]
